### PR TITLE
Update country-list.js

### PR DESCRIPTION
**Pull request by ibmua**
Added XK

### CODE REVIEW

**Comment by EvanHahn** [comment]
I wasn't able to find Kosovo on [Wikipedia's list][1] or [the data on iso.org][2]. Do you have a source I can use to verify whether this is correct?

Also, before I can accept this, you'll need to update [the failing tests](https://travis-ci.org/EvanHahn/iso-3166-country-list/builds/570763592).

[1]: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
[2]: https://www.iso.org/obp/ui/#search

**Comment by ibmua** [comment]
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
The code XK is being used by the European Commission,[24] the IMF, and SWIFT,[25] CLDR and other organizations as a temporary country code for Kosovo.
I ran into this code while working with Maxmind GeoIP.

**Comment by ibmua** [comment]
Reguarding the error, I'm not sure where those tests are and whether I can even access them.

**Comment by EvanHahn** [comment]
"XK" seems nonstandard to me:

- The Wikipedia page says that "XK" is ["user-assigned"](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#XK), implying that it's nonstandard.
- [Eurostat says](https://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Country_codes#cite_note-2) that XR is not an official ISO country code:

  > 'XK' is a code used for practical reasons and not an official ISO country code. 
- The other source on Wikipedia, GeoNames, [makes the same claim](https://geonames.wordpress.com/2010/03/08/xk-country-code-for-kosovo/) about the fact that it's nonstandard:
    > [...] the International Organization for Standardization, ISO, has yet to assign a code to the former Serbian province.

On the other hand, I don't want to disregard Kosovo. What if we documented how to wrap this library to add Kosovo if needed?

**Comment by ibmua** [comment]
I donno, man, up to you. As you can see on the eurostat page, there's actually also a lot of other countries listed as either de-facto used, or candidates. You can make an extended version for those who need such, or something. But it's your project, it's all totally up to you.

**Comment by ibmua** [comment]
I donno, man, up to you. I'm also unsure if Kosovo is the only country used like this, it may make sense to also include other countries, like Palestine. You can make an extended version for those who need such, or something. But it's your project, it's all totally up to you. I personally just parsed your JS object to make an ENUM for my MySQL DB table. IMHO, it really depends on whether a user wants something that includes most all cases, or if he wants to only list some in some weird way politically-correct cases. In my case I just needed something that catched most all cases.

**Comment by EvanHahn** [comment]
Because this module aims to be a reflection of the ISO standard, I'm going to close this pull request. However, I've opened #4 as a task to document how to work with countries not in the ISO standard.

**Pull request closed without merging**
