### PR TITLE
Fix "McDonald McDonald" typo

### PR DESCRIPTION
**Pull request by mszyndel**
"Heard Island and McDonald McDonald Islands" -> "Heard Island and McDonald Islands"

### CODE REVIEW

**Comment by mszyndel** [comment]
@EvanHahn Would be great if you could also release it to npmjs.org!

**Comment by EvanHahn** [comment]
Thanks!

I should be able to look at this tomorrow.

**Comment by mszyndel** [comment]
Thank you for merging, could you please release a new version as well? :)

**Comment by EvanHahn** [comment]
Yes—I'm tidying up the repo and will release in the next 24 hours.

**Comment by EvanHahn** [comment]
Just published `iso-3166-country-list@0.1.2` to npm. Thanks for your contribution!

**Pull request merged**
